#!/bin/bash

USAGE="Usage: $0 FILE COMMAND.."

if [ $# -lt 2 ]; then
	echo "$USAGE"
	exit 1
fi

FILE=$1

shift

CMDSTR="$*"
CMD=$*

function runCmd {
  echo "`date +%T`" ">" $CMDSTR
  $CMD
}

# run the command once at start
runCmd

# and each time the inotify event triggers
while
  inotifywait -e CLOSE_WRITE $FILE &> /dev/null
do
  runCmd
done

